version: 3.0.0.{build}
skip_tags: true
max_jobs: 1
image: Visual Studio 2019
configuration: Release
platform: Any CPU
force_https_clone: true
nuget:
  account_feed: false
  project_feed: false
environment:
  NUGET_HOST: https://www.nuget.org
  NUGET_APIKEY: 
    secure: LBjemyCw2u3Vp5qprTPynswwuvMwydNpGNwNeiycZbbYIAj/+4RFpxbVJirfWmIk
build: off
build_script:
- ps: >-
    dotnet build .\Vivet.AspNetCore.sln;
test: off
artifacts:
- path: '**\*.nupkg'
  name: NuGet Package
deploy:
- provider: NuGet
  server: $(NUGET_HOST)
  api_key: $(NUGET_APIKEY)
  on:
    branch: master
